#!/bin/bash

MAX_LOG_LOSS_MINUTES=15
MIN_LOGS_TO_KEEP_DAYS=30
NO_CONCAT_LOG_FILES_TO_KEEP=$((${MIN_LOGS_TO_KEEP_DAYS} * 24 * 60 / ${MAX_LOG_LOSS_MINUTES}))

STD_OPTS="MAX_LOG_LOSS_MINUTES=${MAX_LOG_LOSS_MINUTES}"
NO_CONCAT_OPTS="${STD_OPTS} MIN_LOG_SIZE_TO_ROTATE=1 LOG_FILES_TO_KEEP=${NO_CONCAT_LOG_FILES_TO_KEEP}"

run_scenario() {
    local CMD="$* ./run-test.sh"
    echo "${CMD}"
    eval "${CMD}"
}

run_scenario COMPRESS=gzip COMPRESS_OPTS=-6 RECOMPRESS=gzip RECOMPRESS_OPTS=-6 ${NO_CONCAT_OPTS}
run_scenario COMPRESS=lzop COMPRESS_OPTS=-3 RECOMPRESS=lzop RECOMPRESS_OPTS=-3 ${NO_CONCAT_OPTS}
run_scenario COMPRESS=lz4 COMPRESS_OPTS=-3 ${STD_OPTS}
run_scenario COMPRESS=lz4 COMPRESS_OPTS=-3 RECOMPRESS=gzip RECOMPRESS_OPTS=-6 ${STD_OPTS}
